### PR TITLE
Update modmenu version

### PR DESCRIPTION
**Pull request by KTibow**
No idea if this will fix it being incompatible, but I tried.

### CODE REVIEW

**Comment by DeathsGun** [comment]
What should this fix?

**Comment by KTibow** [comment]
I *hope* it fixes this.
image

**Comment by DeathsGun** [comment]
Then it's the wrong place to change that.

**Comment by KTibow** [comment]
What do you mean? 3.1.0 is the latest version of Mod Menu, and ironically it's updatable through Mod Manager. If this isn't the right file to change, feel free to close this PR and fix it yourself.

**Comment by DeathsGun** [comment]
It's the right file but if someone uses 3.0.0 and hasn't updated yet it will throw the same error

**Comment by DeathsGun** [comment]
Fixed with 1.2.3+1.18

**Pull request closed without merging**
